package com.uniquindio.thecatapp.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * FavoriteEntity represents both local queued favorite actions and server-synced favorites.
 * - localId: primary key autogenerated for local tracking
 * - id: server id for the favourite (nullable until synced)
 * - imageId: the image identifier the favorite refers to
 * - status: PENDING_ADD | SYNCED | PENDING_DELETE | DELETED
 * - createdAt / updatedAt timestamps
 */
@Entity(tableName = "favorites")
data class FavoriteEntity(
    @PrimaryKey(autoGenerate = true) val localId: Long = 0L,
    val id: Int? = null,
    val imageId: String,
    val status: String,
    val createdAt: Long,
    val updatedAt: Long? = null
)

